// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var dataStructure = DataStructure.FromJson(jsonString);

namespace projekt
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class DataStructure
    {
        [JsonProperty("sitedata")]
        public List<Sitedatum> Sitedata { get; set; }

        [JsonProperty("countryitems")]
        public List<Countryitem> Countryitems { get; set; }
    }

    public partial class Countryitem
    {
        [JsonProperty("1")]
        public The1 The1 { get; set; }

        [JsonProperty("2")]
        public The1 The2 { get; set; }

        [JsonProperty("3")]
        public The1 The3 { get; set; }

        [JsonProperty("4")]
        public The1 The4 { get; set; }

        [JsonProperty("5")]
        public The1 The5 { get; set; }

        [JsonProperty("6")]
        public The1 The6 { get; set; }

        [JsonProperty("7")]
        public The1 The7 { get; set; }

        [JsonProperty("8")]
        public The1 The8 { get; set; }

        [JsonProperty("9")]
        public The1 The9 { get; set; }

        [JsonProperty("10")]
        public The1 The10 { get; set; }

        [JsonProperty("11")]
        public The1 The11 { get; set; }

        [JsonProperty("12")]
        public The1 The12 { get; set; }

        [JsonProperty("13")]
        public The1 The13 { get; set; }

        [JsonProperty("14")]
        public The1 The14 { get; set; }

        [JsonProperty("15")]
        public The1 The15 { get; set; }

        [JsonProperty("16")]
        public The1 The16 { get; set; }

        [JsonProperty("17")]
        public The1 The17 { get; set; }

        [JsonProperty("18")]
        public The1 The18 { get; set; }

        [JsonProperty("19")]
        public The1 The19 { get; set; }

        [JsonProperty("20")]
        public The1 The20 { get; set; }

        [JsonProperty("21")]
        public The1 The21 { get; set; }

        [JsonProperty("22")]
        public The1 The22 { get; set; }

        [JsonProperty("23")]
        public The1 The23 { get; set; }

        [JsonProperty("24")]
        public The1 The24 { get; set; }

        [JsonProperty("25")]
        public The1 The25 { get; set; }

        [JsonProperty("26")]
        public The1 The26 { get; set; }

        [JsonProperty("27")]
        public The1 The27 { get; set; }

        [JsonProperty("28")]
        public The1 The28 { get; set; }

        [JsonProperty("29")]
        public The1 The29 { get; set; }

        [JsonProperty("30")]
        public The1 The30 { get; set; }

        [JsonProperty("31")]
        public The1 The31 { get; set; }

        [JsonProperty("32")]
        public The1 The32 { get; set; }

        [JsonProperty("33")]
        public The1 The33 { get; set; }

        [JsonProperty("34")]
        public The1 The34 { get; set; }

        [JsonProperty("35")]
        public The1 The35 { get; set; }

        [JsonProperty("36")]
        public The1 The36 { get; set; }

        [JsonProperty("37")]
        public The1 The37 { get; set; }

        [JsonProperty("38")]
        public The1 The38 { get; set; }

        [JsonProperty("39")]
        public The1 The39 { get; set; }

        [JsonProperty("40")]
        public The1 The40 { get; set; }

        [JsonProperty("41")]
        public The1 The41 { get; set; }

        [JsonProperty("42")]
        public The1 The42 { get; set; }

        [JsonProperty("43")]
        public The1 The43 { get; set; }

        [JsonProperty("44")]
        public The1 The44 { get; set; }

        [JsonProperty("45")]
        public The1 The45 { get; set; }

        [JsonProperty("46")]
        public The1 The46 { get; set; }

        [JsonProperty("47")]
        public The1 The47 { get; set; }

        [JsonProperty("48")]
        public The1 The48 { get; set; }

        [JsonProperty("49")]
        public The1 The49 { get; set; }

        [JsonProperty("50")]
        public The1 The50 { get; set; }

        [JsonProperty("51")]
        public The1 The51 { get; set; }

        [JsonProperty("52")]
        public The1 The52 { get; set; }

        [JsonProperty("53")]
        public The1 The53 { get; set; }

        [JsonProperty("54")]
        public The1 The54 { get; set; }

        [JsonProperty("55")]
        public The1 The55 { get; set; }

        [JsonProperty("56")]
        public The1 The56 { get; set; }

        [JsonProperty("57")]
        public The1 The57 { get; set; }

        [JsonProperty("58")]
        public The1 The58 { get; set; }

        [JsonProperty("59")]
        public The1 The59 { get; set; }

        [JsonProperty("60")]
        public The1 The60 { get; set; }

        [JsonProperty("61")]
        public The1 The61 { get; set; }

        [JsonProperty("62")]
        public The1 The62 { get; set; }

        [JsonProperty("63")]
        public The1 The63 { get; set; }

        [JsonProperty("64")]
        public The1 The64 { get; set; }

        [JsonProperty("65")]
        public The1 The65 { get; set; }

        [JsonProperty("66")]
        public The1 The66 { get; set; }

        [JsonProperty("67")]
        public The1 The67 { get; set; }

        [JsonProperty("68")]
        public The1 The68 { get; set; }

        [JsonProperty("69")]
        public The1 The69 { get; set; }

        [JsonProperty("70")]
        public The1 The70 { get; set; }

        [JsonProperty("71")]
        public The1 The71 { get; set; }

        [JsonProperty("72")]
        public The1 The72 { get; set; }

        [JsonProperty("73")]
        public The1 The73 { get; set; }

        [JsonProperty("74")]
        public The1 The74 { get; set; }

        [JsonProperty("75")]
        public The1 The75 { get; set; }

        [JsonProperty("76")]
        public The1 The76 { get; set; }

        [JsonProperty("77")]
        public The1 The77 { get; set; }

        [JsonProperty("78")]
        public The1 The78 { get; set; }

        [JsonProperty("79")]
        public The1 The79 { get; set; }

        [JsonProperty("80")]
        public The1 The80 { get; set; }

        [JsonProperty("81")]
        public The1 The81 { get; set; }

        [JsonProperty("82")]
        public The1 The82 { get; set; }

        [JsonProperty("83")]
        public The1 The83 { get; set; }

        [JsonProperty("84")]
        public The1 The84 { get; set; }

        [JsonProperty("85")]
        public The1 The85 { get; set; }

        [JsonProperty("86")]
        public The1 The86 { get; set; }

        [JsonProperty("87")]
        public The1 The87 { get; set; }

        [JsonProperty("88")]
        public The1 The88 { get; set; }

        [JsonProperty("89")]
        public The1 The89 { get; set; }

        [JsonProperty("90")]
        public The1 The90 { get; set; }

        [JsonProperty("91")]
        public The1 The91 { get; set; }

        [JsonProperty("92")]
        public The1 The92 { get; set; }

        [JsonProperty("93")]
        public The1 The93 { get; set; }

        [JsonProperty("94")]
        public The1 The94 { get; set; }

        [JsonProperty("95")]
        public The1 The95 { get; set; }

        [JsonProperty("96")]
        public The1 The96 { get; set; }

        [JsonProperty("97")]
        public The1 The97 { get; set; }

        [JsonProperty("98")]
        public The1 The98 { get; set; }

        [JsonProperty("99")]
        public The1 The99 { get; set; }

        [JsonProperty("100")]
        public The1 The100 { get; set; }

        [JsonProperty("101")]
        public The1 The101 { get; set; }

        [JsonProperty("102")]
        public The1 The102 { get; set; }

        [JsonProperty("103")]
        public The1 The103 { get; set; }

        [JsonProperty("104")]
        public The1 The104 { get; set; }

        [JsonProperty("105")]
        public The1 The105 { get; set; }

        [JsonProperty("106")]
        public The1 The106 { get; set; }

        [JsonProperty("107")]
        public The1 The107 { get; set; }

        [JsonProperty("108")]
        public The1 The108 { get; set; }

        [JsonProperty("109")]
        public The1 The109 { get; set; }

        [JsonProperty("110")]
        public The1 The110 { get; set; }

        [JsonProperty("111")]
        public The1 The111 { get; set; }

        [JsonProperty("112")]
        public The1 The112 { get; set; }

        [JsonProperty("113")]
        public The1 The113 { get; set; }

        [JsonProperty("114")]
        public The1 The114 { get; set; }

        [JsonProperty("115")]
        public The1 The115 { get; set; }

        [JsonProperty("116")]
        public The1 The116 { get; set; }

        [JsonProperty("117")]
        public The1 The117 { get; set; }

        [JsonProperty("118")]
        public The1 The118 { get; set; }

        [JsonProperty("119")]
        public The1 The119 { get; set; }

        [JsonProperty("120")]
        public The1 The120 { get; set; }

        [JsonProperty("121")]
        public The1 The121 { get; set; }

        [JsonProperty("122")]
        public The1 The122 { get; set; }

        [JsonProperty("123")]
        public The1 The123 { get; set; }

        [JsonProperty("124")]
        public The1 The124 { get; set; }

        [JsonProperty("125")]
        public The1 The125 { get; set; }

        [JsonProperty("126")]
        public The1 The126 { get; set; }

        [JsonProperty("127")]
        public The1 The127 { get; set; }

        [JsonProperty("128")]
        public The1 The128 { get; set; }

        [JsonProperty("129")]
        public The1 The129 { get; set; }

        [JsonProperty("130")]
        public The1 The130 { get; set; }

        [JsonProperty("131")]
        public The1 The131 { get; set; }

        [JsonProperty("132")]
        public The1 The132 { get; set; }

        [JsonProperty("133")]
        public The1 The133 { get; set; }

        [JsonProperty("134")]
        public The1 The134 { get; set; }

        [JsonProperty("135")]
        public The1 The135 { get; set; }

        [JsonProperty("136")]
        public The1 The136 { get; set; }

        [JsonProperty("137")]
        public The1 The137 { get; set; }

        [JsonProperty("138")]
        public The1 The138 { get; set; }

        [JsonProperty("139")]
        public The1 The139 { get; set; }

        [JsonProperty("140")]
        public The1 The140 { get; set; }

        [JsonProperty("141")]
        public The1 The141 { get; set; }

        [JsonProperty("142")]
        public The1 The142 { get; set; }

        [JsonProperty("143")]
        public The1 The143 { get; set; }

        [JsonProperty("144")]
        public The1 The144 { get; set; }

        [JsonProperty("145")]
        public The1 The145 { get; set; }

        [JsonProperty("146")]
        public The1 The146 { get; set; }

        [JsonProperty("147")]
        public The1 The147 { get; set; }

        [JsonProperty("148")]
        public The1 The148 { get; set; }

        [JsonProperty("149")]
        public The1 The149 { get; set; }

        [JsonProperty("150")]
        public The1 The150 { get; set; }

        [JsonProperty("151")]
        public The1 The151 { get; set; }

        [JsonProperty("152")]
        public The1 The152 { get; set; }

        [JsonProperty("153")]
        public The1 The153 { get; set; }

        [JsonProperty("154")]
        public The1 The154 { get; set; }

        [JsonProperty("155")]
        public The1 The155 { get; set; }

        [JsonProperty("156")]
        public The1 The156 { get; set; }

        [JsonProperty("157")]
        public The1 The157 { get; set; }

        [JsonProperty("158")]
        public The1 The158 { get; set; }

        [JsonProperty("159")]
        public The1 The159 { get; set; }

        [JsonProperty("160")]
        public The1 The160 { get; set; }

        [JsonProperty("161")]
        public The1 The161 { get; set; }

        [JsonProperty("162")]
        public The1 The162 { get; set; }

        [JsonProperty("163")]
        public The1 The163 { get; set; }

        [JsonProperty("164")]
        public The1 The164 { get; set; }

        [JsonProperty("165")]
        public The1 The165 { get; set; }

        [JsonProperty("166")]
        public The1 The166 { get; set; }

        [JsonProperty("167")]
        public The1 The167 { get; set; }

        [JsonProperty("168")]
        public The1 The168 { get; set; }

        [JsonProperty("169")]
        public The1 The169 { get; set; }

        [JsonProperty("170")]
        public The1 The170 { get; set; }

        [JsonProperty("171")]
        public The1 The171 { get; set; }

        [JsonProperty("172")]
        public The1 The172 { get; set; }

        [JsonProperty("173")]
        public The1 The173 { get; set; }

        [JsonProperty("174")]
        public The1 The174 { get; set; }

        [JsonProperty("175")]
        public The1 The175 { get; set; }

        [JsonProperty("176")]
        public The1 The176 { get; set; }

        [JsonProperty("177")]
        public The1 The177 { get; set; }

        [JsonProperty("178")]
        public The1 The178 { get; set; }

        [JsonProperty("179")]
        public The1 The179 { get; set; }

        [JsonProperty("180")]
        public The1 The180 { get; set; }

        [JsonProperty("181")]
        public The1 The181 { get; set; }

        [JsonProperty("182")]
        public The1 The182 { get; set; }

        [JsonProperty("stat")]
        public string Stat { get; set; }
    }

    public partial class The1
    {
        [JsonProperty("ourid")]
        public long Ourid { get; set; }

        [JsonProperty("title")]
        public string Title { get; set; }

        [JsonProperty("code")]
        public string Code { get; set; }

        [JsonProperty("source")]
        public Uri Source { get; set; }

        [JsonProperty("total_cases")]
        public long TotalCases { get; set; }

        [JsonProperty("total_recovered")]
        public long TotalRecovered { get; set; }

        [JsonProperty("total_unresolved")]
        public long TotalUnresolved { get; set; }

        [JsonProperty("total_deaths")]
        public long TotalDeaths { get; set; }

        [JsonProperty("total_new_cases_today")]
        public long TotalNewCasesToday { get; set; }

        [JsonProperty("total_new_deaths_today")]
        public long TotalNewDeathsToday { get; set; }

        [JsonProperty("total_active_cases")]
        public long TotalActiveCases { get; set; }

        [JsonProperty("total_serious_cases")]
        public long TotalSeriousCases { get; set; }
    }

    public partial class Sitedatum
    {
        [JsonProperty("info")]
        public Info Info { get; set; }
    }

    public partial class Info
    {
        [JsonProperty("source")]
        public Uri Source { get; set; }
    }

    public partial class DataStructure
    {
        public static DataStructure FromJson(string json) => JsonConvert.DeserializeObject<DataStructure>(json, projekt.Converter.Settings);
    }

    public static class Serialize
    {
        public static string ToJson(this DataStructure self) => JsonConvert.SerializeObject(self, projekt.Converter.Settings);
    }

    internal static class Converter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }
}
